POST https://node-test-g2g8.onrender.com/videos
Content-Type: application/json

{
    "title": "adasdasd",
    "description": "This is a video",
    "duration": 180
}

###

get https://node-test-g2g8.onrender.com/videos?search=

###

put https://node-test-g2g8.onrender.com/videos/f582b22d-ab13-426f-8101-25778a8282d4
Content-Type: application/json

{
    "title": "AI KRL",
    "description": "This is a video",
    "duration": 180
}

###

DELETE https://node-test-g2g8.onrender.com/videos/f582b22d-ab13-426f-8101-25778a8282d4