POST https://node-do-zero-server-latest.onrender.com/videos
Content-Type: application/json

{
    "title": "ui",
    "description": "This is a video",
    "duration": 180
}

###

get https://node-do-zero-server-latest.onrender.com/videos?search=

###

put https://node-do-zero-server-latest.onrender.com/videos/f582b22d-ab13-426f-8101-25778a8282d4
Content-Type: application/json

{
    "title": "AI KRL",
    "description": "This is a video",
    "duration": 180
}

###

DELETE https://node-do-zero-server-latest.onrender.com/videos/05a9fc14-14b5-4021-8d84-efc54aecd523