POST http://localhost:3000/videos
Content-Type: application/json

{
    "title": "My Video 2",
    "description": "This is a video",
    "duration": 180
}

###

get http://localhost:3000/videos?search=

###

put http://localhost:3000/videos/f582b22d-ab13-426f-8101-25778a8282d4
Content-Type: application/json

{
    "title": "AI KRL",
    "description": "This is a video",
    "duration": 180
}

###

DELETE http://localhost:3000/videos/f582b22d-ab13-426f-8101-25778a8282d4